In [1]:
 #This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns; sns.set(style="ticks", color_codes=True)
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesRegressor, RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.feature_selection import RFE
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import KFold
import matplotlib.pyplot as plt

In [2]:
import os
print(os.listdir("/Users/saurabhbhise/Documents/Study/Statistical Data Analysis/Walmart Python Solution"))

['outputextratreeregressor.csv', '.DS_Store', 'sampleSubmission.csv', 'outputknn.csv', 'Untitled.ipynb', 'outputraaaandomforest.csv', 'Walmart Python.ipynb', 'test.csv', 'statgeha.docx', 'train.csv', '.ipynb_checkpoints', 'outputrandom forest.csv', 'features.csv', '~$atgeha.docx', 'stores.csv']

In [3]:
dataset = pd.read_csv("../Walmart Python Solution/train.csv", names=['Store','Dept','Date','weeklySales','isHoliday'],sep=',', header=0)
features = pd.read_csv("../Walmart Python Solution/features.csv",sep=',', header=0,
                       names=['Store','Date','Temperature','Fuel_Price','MarkDown1','MarkDown2','MarkDown3','MarkDown4',
                              'MarkDown5','CPI','Unemployment','IsHoliday']).drop(columns=['IsHoliday'])
stores = pd.read_csv("../Walmart Python Solution/stores.csv", names=['Store','Type','Size'],sep=',', header=0)
dataset = dataset.merge(stores, how='left').merge(features, how='left')

# dataset["nextWeekHoliday"] = dataset["isHoliday"].shift(-1).fillna(False)
# dataset["next2WeekHoliday"] = dataset["isHoliday"].shift(-2).fillna(False)
dataset

,Store,Dept,Date,weeklySales,isHoliday,Type,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,1,2010-02-05,24924.50,False,A,151315,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106
1,1,1,2010-02-12,46039.49,True,A,151315,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106
2,1,1,2010-02-19,41595.55,False,A,151315,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106
3,1,1,2010-02-26,19403.54,False,A,151315,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106
4,1,1,2010-03-05,21827.90,False,A,151315,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106
5,1,1,2010-03-12,21043.39,False,A,151315,57.79,2.667,NaN,NaN,NaN,NaN,NaN,211.380643,8.106
6,1,1,2010-03-19,22136.64,False,A,151315,54.58,2.720,NaN,NaN,NaN,NaN,NaN,211.215635,8.106
7,1,1,2010-03-26,26229.21,False,A,151315,51.45,2.732,NaN,NaN,NaN,NaN,NaN,211.018042,8.106
8,1,1,2010-04-02,57258.43,False,A,151315,62.27,2.719,NaN,NaN,NaN,NaN,NaN,210.820450,7.808
9,1,1,2010-04-09,42960.91,False,A,151315,65.86,2.770,NaN,NaN,NaN,NaN,NaN,210.622857,7.808
10,1,1,2010-04-16,17596.96,False,A,151315,66.32,2.808,NaN,NaN,NaN,NaN,NaN,210.488700,7.808
11,1,1,2010-04-23,16145.35,False,A,151315,64.84,2.795,NaN,NaN,NaN,NaN,NaN,210.439123,7.808
12,1,1,2010-04-30,16555.11,False,A,151315,67.41,2.780,NaN,NaN,NaN,NaN,NaN,210.389546,7.808
13,1,1,2010-05-07,17413.94,False,A,151315,72.55,2.835,NaN,NaN,NaN,NaN,NaN,210.339968,7.808
14,1,1,2010-05-14,18926.74,False,A,151315,74.78,2.854,NaN,NaN,NaN,NaN,NaN,210.337426,7.808
15,1,1,2010-05-21,14773.04,False,A,151315,76.44,2.826,NaN,NaN,NaN,NaN,NaN,210.617093,7.808
16,1,1,2010-05-28,15580.43,False,A,151315,80.44,2.759,NaN,NaN,NaN,NaN,NaN,210.896761,7.808
17,1,1,2010-06-04,17558.09,False,A,151315,80.69,2.705,NaN,NaN,NaN,NaN,NaN,211.176428,7.808
18,1,1,2010-06-11,16637.62,False,A,151315,80.43,2.668,NaN,NaN,NaN,NaN,NaN,211.456095,7.808
19,1,1,2010-06-18,16216.27,False,A,151315,84.11,2.637,NaN,NaN,NaN,NaN,NaN,211.453772,7.808
20,1,1,2010-06-25,16328.72,False,A,151315,84.34,2.653,NaN,NaN,NaN,NaN,NaN,211.338653,7.808
21,1,1,2010-07-02,16333.14,False,A,151315,80.91,2.669,NaN,NaN,NaN,NaN,NaN,211.223533,7.787
22,1,1,2010-07-09,17688.76,False,A,151315,80.48,2.642,NaN,NaN,NaN,NaN,NaN,211.108414,7.787
23,1,1,2010-07-16,17150.84,False,A,151315,83.15,2.623,NaN,NaN,NaN,NaN,NaN,211.100385,7.787
24,1,1,2010-07-23,15360.45,False,A,151315,83.36,2.608,NaN,NaN,NaN,NaN,NaN,211.235144,7.787
25,1,1,2010-07-30,15381.82,False,A,151315,81.84,2.640,NaN,NaN,NaN,NaN,NaN,211.369903,7.787
26,1,1,2010-08-06,17508.41,False,A,151315,87.16,2.627,NaN,NaN,NaN,NaN,NaN,211.504662,7.787
27,1,1,2010-08-13,15536.40,False,A,151315,87.00,2.692,NaN,NaN,NaN,NaN,NaN,211.639421,7.787
28,1,1,2010-08-20,15740.13,False,A,151315,86.65,2.664,NaN,NaN,NaN,NaN,NaN,211.603363,7.787
29,1,1,2010-08-27,15793.87,False,A,151315,85.22,2.619,NaN,NaN,NaN,NaN,NaN,211.567306,7.787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421540,45,98,2012-04-06,778.70,False,B,118221,49.73,3.996,13450.45,NaN,26.59,3363.54,3962.01,190.685171,8.567
421541,45,98,2012-04-13,559.14,False,B,118221,51.83,4.044,4736.94,6047.12,16.68,1355.11,2246.12,190.759596,8.567
421542,45,98,2012-04-20,605.80,False,B,118221,63.13,4.027,9210.90,2667.05,6.25,970.33,2568.22,190.813801,8.567
421543,45,98,2012-04-27,619.41,False,B,118221,53.20,4.004,2872.86,0.03,37.12,74.97,2495.29,190.868006,8.567
421544,45,98,2012-05-04,694.25,False,B,118221,55.21,3.951,11984.62,NaN,47.52,6150.63,1775.54,190.922212,8.567
421545,45,98,2012-05-11,893.60,False,B,118221,61.24,3.889,12611.18,NaN,21.36,1667.39,2313.12,190.976417,8.567
421546,45,98,2012-05-18,745.44,False,B,118221,66.30,3.848,6813.74,NaN,13.86,936.49,2941.55,190.996448,8.567
421547,45,98,2012-05-25,795.94,False,B,118221,67.21,3.798,5370.39,NaN,361.22,1287.62,2461.81,191.002810,8.567
421548,45,98,2012-06-01,874.64,False,B,118221,74.48,3.742,10643.62,48.20,201.56,2599.35,1856.97,191.009171,8.567
421549,45,98,2012-06-08,713.50,False,B,118221,64.30,3.689,8429.61,148.60,76.15,1465.54,7180.97,191.015533,8.567
421550,45,98,2012-06-15,856.35,False,B,118221,71.93,3.620,8148.19,252.70,90.05,1226.11,2942.39,191.029973,8.567
421551,45,98,2012-06-22,622.62,False,B,118221,74.22,3.564,5565.31,222.50,1.16,2149.76,7474.76,191.064610,8.567
421552,45,98,2012-06-29,690.52,False,B,118221,75.22,3.506,3291.36,425.60,NaN,314.88,2255.34,191.099246,8.567
421553,45,98,2012-07-06,659.65,False,B,118221,82.99,3.475,5878.09,169.00,64.36,2996.47,5477.04,191.133883,8.684
421554,45,98,2012-07-13,695.21,False,B,118221,79.97,3.523,2978.08,118.90,22.07,1899.54,5181.94,191.168519,8.684
421555,45,98,2012-07-20,845.30,False,B,118221,78.89,3.567,6682.75,24.24,12.83,2249.85,2288.30,191.167043,8.684
421556,45,98,2012-07-27,657.63,False,B,118221,77.20,3.647,5753.81,167.95,1.23,9181.48,3156.06,191.165566,8.684
421557,45,98,2012-08-03,516.46,False,B,118221,76.58,3.654,24853.05,39.56,17.96,11142.69,2768.32,191.164090,8.684
421558,45,98,2012-08-10,727.49,False,B,118221,78.65,3.722,17868.84,50.60,57.66,2593.93,1890.59,191.162613,8.684
421559,45,98,2012-08-17,500.16,False,B,118221,75.71,3.807,3657.79,6.00,0.30,1630.50,3794.22,191.228492,8.684
421560,45,98,2012-08-24,415.40,False,B,118221,72.62,3.834,7936.20,58.38,22.00,5518.07,2291.97,191.344887,8.684
421561,45,98,2012-08-31,346.04,False,B,118221,75.09,3.867,23641.30,6.00,92.93,6988.31,3992.13,191.461281,8.684
421562,45,98,2012-09-07,352.44,True,B,118221,75.70,3.911,11024.45,12.80,52.63,1854.77,2055.70,191.577676,8.684
421563,45,98,2012-09-14,605.96,False,B,118221,67.87,3.948,11407.95,NaN,4.30,3421.72,5268.92,191.699850,8.684
421564,45,98,2012-09-21,467.30,False,B,118221,65.32,4.038,8452.20,92.28,63.24,2376.38,8670.40,191.856704,8.684
421565,45,98,2012-09-28,508.37,False,B,118221,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684
421566,45,98,2012-10-05,628.10,False,B,118221,64.89,3.985,5046.74,NaN,18.82,2253.43,2340.01,192.170412,8.667
421567,45,98,2012-10-12,1061.02,False,B,118221,54.47,4.000,1956.28,NaN,7.89,599.32,3990.54,192.327265,8.667
421568,45,98,2012-10-19,760.01,False,B,118221,56.47,3.969,2004.02,NaN,3.18,437.73,1537.49,192.330854,8.667
421569,45,98,2012-10-26,1076.80,False,B,118221,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667

In [4]:
import pandas as pd


dataset = pd.get_dummies(dataset, columns=["Type"])
dataset[['MarkDown1','MarkDown2','MarkDown3','MarkDown4', 'MarkDown5']] = dataset[['MarkDown1','MarkDown2','MarkDown3','MarkDown4','MarkDown5']].fillna(0)
dataset['Month'] = pd.to_datetime(dataset['Date']).dt.month
dataset = dataset.drop(columns=["Date", "CPI", "Fuel_Price", 'Unemployment', 'MarkDown3'])
dataset

,Store,Dept,weeklySales,isHoliday,Size,Temperature,MarkDown1,MarkDown2,MarkDown4,MarkDown5,Type_A,Type_B,Type_C,Month
0,1,1,24924.50,False,151315,42.31,0.00,0.00,0.00,0.00,1,0,0,2
1,1,1,46039.49,True,151315,38.51,0.00,0.00,0.00,0.00,1,0,0,2
2,1,1,41595.55,False,151315,39.93,0.00,0.00,0.00,0.00,1,0,0,2
3,1,1,19403.54,False,151315,46.63,0.00,0.00,0.00,0.00,1,0,0,2
4,1,1,21827.90,False,151315,46.50,0.00,0.00,0.00,0.00,1,0,0,3
5,1,1,21043.39,False,151315,57.79,0.00,0.00,0.00,0.00,1,0,0,3
6,1,1,22136.64,False,151315,54.58,0.00,0.00,0.00,0.00,1,0,0,3
7,1,1,26229.21,False,151315,51.45,0.00,0.00,0.00,0.00,1,0,0,3
8,1,1,57258.43,False,151315,62.27,0.00,0.00,0.00,0.00,1,0,0,4
9,1,1,42960.91,False,151315,65.86,0.00,0.00,0.00,0.00,1,0,0,4
10,1,1,17596.96,False,151315,66.32,0.00,0.00,0.00,0.00,1,0,0,4
11,1,1,16145.35,False,151315,64.84,0.00,0.00,0.00,0.00,1,0,0,4
12,1,1,16555.11,False,151315,67.41,0.00,0.00,0.00,0.00,1,0,0,4
13,1,1,17413.94,False,151315,72.55,0.00,0.00,0.00,0.00,1,0,0,5
14,1,1,18926.74,False,151315,74.78,0.00,0.00,0.00,0.00,1,0,0,5
15,1,1,14773.04,False,151315,76.44,0.00,0.00,0.00,0.00,1,0,0,5
16,1,1,15580.43,False,151315,80.44,0.00,0.00,0.00,0.00,1,0,0,5
17,1,1,17558.09,False,151315,80.69,0.00,0.00,0.00,0.00,1,0,0,6
18,1,1,16637.62,False,151315,80.43,0.00,0.00,0.00,0.00,1,0,0,6
19,1,1,16216.27,False,151315,84.11,0.00,0.00,0.00,0.00,1,0,0,6
20,1,1,16328.72,False,151315,84.34,0.00,0.00,0.00,0.00,1,0,0,6
21,1,1,16333.14,False,151315,80.91,0.00,0.00,0.00,0.00,1,0,0,7
22,1,1,17688.76,False,151315,80.48,0.00,0.00,0.00,0.00,1,0,0,7
23,1,1,17150.84,False,151315,83.15,0.00,0.00,0.00,0.00,1,0,0,7
24,1,1,15360.45,False,151315,83.36,0.00,0.00,0.00,0.00,1,0,0,7
25,1,1,15381.82,False,151315,81.84,0.00,0.00,0.00,0.00,1,0,0,7
26,1,1,17508.41,False,151315,87.16,0.00,0.00,0.00,0.00,1,0,0,8
27,1,1,15536.40,False,151315,87.00,0.00,0.00,0.00,0.00,1,0,0,8
28,1,1,15740.13,False,151315,86.65,0.00,0.00,0.00,0.00,1,0,0,8
29,1,1,15793.87,False,151315,85.22,0.00,0.00,0.00,0.00,1,0,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421540,45,98,778.70,False,118221,49.73,13450.45,0.00,3363.54,3962.01,0,1,0,4
421541,45,98,559.14,False,118221,51.83,4736.94,6047.12,1355.11,2246.12,0,1,0,4
421542,45,98,605.80,False,118221,63.13,9210.90,2667.05,970.33,2568.22,0,1,0,4
421543,45,98,619.41,False,118221,53.20,2872.86,0.03,74.97,2495.29,0,1,0,4
421544,45,98,694.25,False,118221,55.21,11984.62,0.00,6150.63,1775.54,0,1,0,5
421545,45,98,893.60,False,118221,61.24,12611.18,0.00,1667.39,2313.12,0,1,0,5
421546,45,98,745.44,False,118221,66.30,6813.74,0.00,936.49,2941.55,0,1,0,5
421547,45,98,795.94,False,118221,67.21,5370.39,0.00,1287.62,2461.81,0,1,0,5
421548,45,98,874.64,False,118221,74.48,10643.62,48.20,2599.35,1856.97,0,1,0,6
421549,45,98,713.50,False,118221,64.30,8429.61,148.60,1465.54,7180.97,0,1,0,6
421550,45,98,856.35,False,118221,71.93,8148.19,252.70,1226.11,2942.39,0,1,0,6
421551,45,98,622.62,False,118221,74.22,5565.31,222.50,2149.76,7474.76,0,1,0,6
421552,45,98,690.52,False,118221,75.22,3291.36,425.60,314.88,2255.34,0,1,0,6
421553,45,98,659.65,False,118221,82.99,5878.09,169.00,2996.47,5477.04,0,1,0,7
421554,45,98,695.21,False,118221,79.97,2978.08,118.90,1899.54,5181.94,0,1,0,7
421555,45,98,845.30,False,118221,78.89,6682.75,24.24,2249.85,2288.30,0,1,0,7
421556,45,98,657.63,False,118221,77.20,5753.81,167.95,9181.48,3156.06,0,1,0,7
421557,45,98,516.46,False,118221,76.58,24853.05,39.56,11142.69,2768.32,0,1,0,8
421558,45,98,727.49,False,118221,78.65,17868.84,50.60,2593.93,1890.59,0,1,0,8
421559,45,98,500.16,False,118221,75.71,3657.79,6.00,1630.50,3794.22,0,1,0,8
421560,45,98,415.40,False,118221,72.62,7936.20,58.38,5518.07,2291.97,0,1,0,8
421561,45,98,346.04,False,118221,75.09,23641.30,6.00,6988.31,3992.13,0,1,0,8
421562,45,98,352.44,True,118221,75.70,11024.45,12.80,1854.77,2055.70,0,1,0,9
421563,45,98,605.96,False,118221,67.87,11407.95,0.00,3421.72,5268.92,0,1,0,9
421564,45,98,467.30,False,118221,65.32,8452.20,92.28,2376.38,8670.40,0,1,0,9
421565,45,98,508.37,False,118221,64.88,4556.61,20.64,1601.01,3288.25,0,1,0,9
421566,45,98,628.10,False,118221,64.89,5046.74,0.00,2253.43,2340.01,0,1,0,10
421567,45,98,1061.02,False,118221,54.47,1956.28,0.00,599.32,3990.54,0,1,0,10
421568,45,98,760.01,False,118221,56.47,2004.02,0.00,437.73,1537.49,0,1,0,10
421569,45,98,1076.80,False,118221,58.85,4018.91,58.08,211.94,858.33,0,1,0,10

In [5]:
#def randomForestRegressor():
#    clf = RandomForestRegressor(n_estimators=100,max_features='log2', verbose=1)
#    return clf

def knn():
    knn = KNeighborsRegressor(n_neighbors=10)
    return knn

def predict_(m, test_x):
    return pd.Series(m.predict(test_x))

def model_():
     return knn()
#    return extraTreesRegressor()
#     return svm()
#     return nn()
#     return randomForestRegressor()
 

def train_(train_x, train_y):
    m = model_()
    m.fit(train_x, train_y)
    return m

def train_and_predict(train_x, train_y, test_x):
    m = train_(train_x, train_y)
    return predict_(m, test_x), m

In [6]:
def calculate_error(test_y, predicted, weights):
    return mean_absolute_error(test_y, predicted, sample_weight=weights)

In [7]:
kf = KFold(n_splits=5)
splited = []
# dataset2 = dataset.copy()
for name, group in dataset.groupby(["Store", "Dept"]):
    group = group.reset_index(drop=True)
    trains_x = []
    trains_y = []
    tests_x = []
    tests_y = []
    if group.shape[0] <= 5:
        f = np.array(range(5))
        np.random.shuffle(f)
        group['fold'] = f[:group.shape[0]]
        continue
    fold = 0
    for train_index, test_index in kf.split(group):
        group.loc[test_index, 'fold'] = fold
        fold += 1
    splited.append(group)

splited = pd.concat(splited).reset_index(drop=True)

In [8]:
splited

,Store,Dept,weeklySales,isHoliday,Size,Temperature,MarkDown1,MarkDown2,MarkDown4,MarkDown5,Type_A,Type_B,Type_C,Month,fold
0,1,1,24924.50,False,151315,42.31,0.00,0.00,0.00,0.00,1,0,0,2,0.0
1,1,1,46039.49,True,151315,38.51,0.00,0.00,0.00,0.00,1,0,0,2,0.0
2,1,1,41595.55,False,151315,39.93,0.00,0.00,0.00,0.00,1,0,0,2,0.0
3,1,1,19403.54,False,151315,46.63,0.00,0.00,0.00,0.00,1,0,0,2,0.0
4,1,1,21827.90,False,151315,46.50,0.00,0.00,0.00,0.00,1,0,0,3,0.0
5,1,1,21043.39,False,151315,57.79,0.00,0.00,0.00,0.00,1,0,0,3,0.0
6,1,1,22136.64,False,151315,54.58,0.00,0.00,0.00,0.00,1,0,0,3,0.0
7,1,1,26229.21,False,151315,51.45,0.00,0.00,0.00,0.00,1,0,0,3,0.0
8,1,1,57258.43,False,151315,62.27,0.00,0.00,0.00,0.00,1,0,0,4,0.0
9,1,1,42960.91,False,151315,65.86,0.00,0.00,0.00,0.00,1,0,0,4,0.0
10,1,1,17596.96,False,151315,66.32,0.00,0.00,0.00,0.00,1,0,0,4,0.0
11,1,1,16145.35,False,151315,64.84,0.00,0.00,0.00,0.00,1,0,0,4,0.0
12,1,1,16555.11,False,151315,67.41,0.00,0.00,0.00,0.00,1,0,0,4,0.0
13,1,1,17413.94,False,151315,72.55,0.00,0.00,0.00,0.00,1,0,0,5,0.0
14,1,1,18926.74,False,151315,74.78,0.00,0.00,0.00,0.00,1,0,0,5,0.0
15,1,1,14773.04,False,151315,76.44,0.00,0.00,0.00,0.00,1,0,0,5,0.0
16,1,1,15580.43,False,151315,80.44,0.00,0.00,0.00,0.00,1,0,0,5,0.0
17,1,1,17558.09,False,151315,80.69,0.00,0.00,0.00,0.00,1,0,0,6,0.0
18,1,1,16637.62,False,151315,80.43,0.00,0.00,0.00,0.00,1,0,0,6,0.0
19,1,1,16216.27,False,151315,84.11,0.00,0.00,0.00,0.00,1,0,0,6,0.0
20,1,1,16328.72,False,151315,84.34,0.00,0.00,0.00,0.00,1,0,0,6,0.0
21,1,1,16333.14,False,151315,80.91,0.00,0.00,0.00,0.00,1,0,0,7,0.0
22,1,1,17688.76,False,151315,80.48,0.00,0.00,0.00,0.00,1,0,0,7,0.0
23,1,1,17150.84,False,151315,83.15,0.00,0.00,0.00,0.00,1,0,0,7,0.0
24,1,1,15360.45,False,151315,83.36,0.00,0.00,0.00,0.00,1,0,0,7,0.0
25,1,1,15381.82,False,151315,81.84,0.00,0.00,0.00,0.00,1,0,0,7,0.0
26,1,1,17508.41,False,151315,87.16,0.00,0.00,0.00,0.00,1,0,0,8,0.0
27,1,1,15536.40,False,151315,87.00,0.00,0.00,0.00,0.00,1,0,0,8,0.0
28,1,1,15740.13,False,151315,86.65,0.00,0.00,0.00,0.00,1,0,0,8,0.0
29,1,1,15793.87,False,151315,85.22,0.00,0.00,0.00,0.00,1,0,0,8,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421244,45,98,778.70,False,118221,49.73,13450.45,0.00,3363.54,3962.01,0,1,0,4,3.0
421245,45,98,559.14,False,118221,51.83,4736.94,6047.12,1355.11,2246.12,0,1,0,4,3.0
421246,45,98,605.80,False,118221,63.13,9210.90,2667.05,970.33,2568.22,0,1,0,4,3.0
421247,45,98,619.41,False,118221,53.20,2872.86,0.03,74.97,2495.29,0,1,0,4,4.0
421248,45,98,694.25,False,118221,55.21,11984.62,0.00,6150.63,1775.54,0,1,0,5,4.0
421249,45,98,893.60,False,118221,61.24,12611.18,0.00,1667.39,2313.12,0,1,0,5,4.0
421250,45,98,745.44,False,118221,66.30,6813.74,0.00,936.49,2941.55,0,1,0,5,4.0
421251,45,98,795.94,False,118221,67.21,5370.39,0.00,1287.62,2461.81,0,1,0,5,4.0
421252,45,98,874.64,False,118221,74.48,10643.62,48.20,2599.35,1856.97,0,1,0,6,4.0
421253,45,98,713.50,False,118221,64.30,8429.61,148.60,1465.54,7180.97,0,1,0,6,4.0
421254,45,98,856.35,False,118221,71.93,8148.19,252.70,1226.11,2942.39,0,1,0,6,4.0
421255,45,98,622.62,False,118221,74.22,5565.31,222.50,2149.76,7474.76,0,1,0,6,4.0
421256,45,98,690.52,False,118221,75.22,3291.36,425.60,314.88,2255.34,0,1,0,6,4.0
421257,45,98,659.65,False,118221,82.99,5878.09,169.00,2996.47,5477.04,0,1,0,7,4.0
421258,45,98,695.21,False,118221,79.97,2978.08,118.90,1899.54,5181.94,0,1,0,7,4.0
421259,45,98,845.30,False,118221,78.89,6682.75,24.24,2249.85,2288.30,0,1,0,7,4.0
421260,45,98,657.63,False,118221,77.20,5753.81,167.95,9181.48,3156.06,0,1,0,7,4.0
421261,45,98,516.46,False,118221,76.58,24853.05,39.56,11142.69,2768.32,0,1,0,8,4.0
421262,45,98,727.49,False,118221,78.65,17868.84,50.60,2593.93,1890.59,0,1,0,8,4.0
421263,45,98,500.16,False,118221,75.71,3657.79,6.00,1630.50,3794.22,0,1,0,8,4.0
421264,45,98,415.40,False,118221,72.62,7936.20,58.38,5518.07,2291.97,0,1,0,8,4.0
421265,45,98,346.04,False,118221,75.09,23641.30,6.00,6988.31,3992.13,0,1,0,8,4.0
421266,45,98,352.44,True,118221,75.70,11024.45,12.80,1854.77,2055.70,0,1,0,9,4.0
421267,45,98,605.96,False,118221,67.87,11407.95,0.00,3421.72,5268.92,0,1,0,9,4.0
421268,45,98,467.30,False,118221,65.32,8452.20,92.28,2376.38,8670.40,0,1,0,9,4.0
421269,45,98,508.37,False,118221,64.88,4556.61,20.64,1601.01,3288.25,0,1,0,9,4.0
421270,45,98,628.10,False,118221,64.89,5046.74,0.00,2253.43,2340.01,0,1,0,10,4.0
421271,45,98,1061.02,False,118221,54.47,1956.28,0.00,599.32,3990.54,0,1,0,10,4.0
421272,45,98,760.01,False,118221,56.47,2004.02,0.00,437.73,1537.49,0,1,0,10,4.0
421273,45,98,1076.80,False,118221,58.85,4018.91,58.08,211.94,858.33,0,1,0,10,4.0

In [9]:
best_model = None
error_cv = 0
best_error = np.iinfo(np.int32).max
for fold in range(5):
    dataset_train = splited.loc[splited['fold'] != fold]
    dataset_test = splited.loc[splited['fold'] == fold]
    train_y = dataset_train['weeklySales']
    train_x = dataset_train.drop(columns=['weeklySales', 'fold'])
    test_y = dataset_test['weeklySales']
    test_x = dataset_test.drop(columns=['weeklySales', 'fold'])
    print(dataset_train.shape, dataset_test.shape)
    predicted, model = train_and_predict(train_x, train_y, test_x)
    weights = test_x['isHoliday'].replace(True, 5).replace(False, 1)
    error = calculate_error(test_y, predicted, weights)
    error_cv += error
    print(fold, error)
    if error < best_error:
        print('Find best model')
        best_error = error
        best_model = model
error_cv /= 5

(335722, 15) (85552, 15)
0 8250.480564572035
Find best model
(335849, 15) (85425, 15)
1 9833.958650796905
(335970, 15) (85304, 15)
2 8020.284378148511
Find best model
(338733, 15) (82541, 15)
3 13497.729240898076
(338822, 15) (82452, 15)
4 11788.863562489421

In [10]:
error_cv

10278.26327938099

In [11]:
best_error

8020.284378148511

In [12]:
dataset_test = pd.read_csv("../Walmart Python Solution/test.csv", names=['Store','Dept','Date','isHoliday'],sep=',', header=0)
features = pd.read_csv("../Walmart Python Solution/features.csv",sep=',', header=0,
                       names=['Store','Date','Temperature','Fuel_Price','MarkDown1','MarkDown2','MarkDown3','MarkDown4',
                              'MarkDown5','CPI','Unemployment','IsHoliday']).drop(columns=['IsHoliday'])
stores = pd.read_csv("../Walmart Python Solution/stores.csv", names=['Store','Type','Size'],sep=',', header=0)
dataset_test = dataset_test.merge(stores, how='left').merge(features, how='left')

In [13]:
dataset_test = pd.get_dummies(dataset_test, columns=["Type"])
dataset_test[['MarkDown1','MarkDown2','MarkDown3','MarkDown4', 'MarkDown5']] = dataset_test[['MarkDown1','MarkDown2','MarkDown3','MarkDown4','MarkDown5']].fillna(0)
dataset_test = dataset_test.fillna(0)
column_date = dataset_test['Date']
dataset_test['Month'] = pd.to_datetime(dataset_test['Date']).dt.month
dataset_test = dataset_test.drop(columns=["Date", "CPI", "Fuel_Price", 'Unemployment', 'MarkDown3'])
dataset_test

,Store,Dept,isHoliday,Size,Temperature,MarkDown1,MarkDown2,MarkDown4,MarkDown5,Type_A,Type_B,Type_C,Month
0,1,1,False,151315,55.32,6766.44,5147.70,3639.90,2737.42,1,0,0,11
1,1,1,False,151315,61.24,11421.32,3370.89,4646.79,6154.16,1,0,0,11
2,1,1,False,151315,52.92,9696.28,292.10,1133.15,6612.69,1,0,0,11
3,1,1,True,151315,56.23,883.59,4.17,209.91,303.32,1,0,0,11
4,1,1,False,151315,52.34,2460.03,0.00,150.57,6966.34,1,0,0,11
5,1,1,False,151315,64.12,6343.16,0.00,2928.90,10147.90,1,0,0,12
6,1,1,False,151315,48.89,3504.83,0.00,1636.80,2779.60,1,0,0,12
7,1,1,False,151315,56.02,8231.71,0.00,358.15,2834.02,1,0,0,12
8,1,1,True,151315,44.79,12659.55,37101.13,74.46,1208.86,1,0,0,12
9,1,1,False,151315,41.73,1214.08,25366.33,72.36,3940.02,1,0,0,1
10,1,1,False,151315,50.32,6520.24,16134.60,774.55,4001.25,1,0,0,1
11,1,1,False,151315,42.92,3772.69,3559.46,246.62,1900.40,1,0,0,1
12,1,1,False,151315,53.37,965.89,1097.91,225.36,1831.88,1,0,0,1
13,1,1,False,151315,56.46,9290.91,1359.90,20657.82,972.61,1,0,0,2
14,1,1,True,151315,56.67,32355.16,729.80,20426.61,4671.78,1,0,0,2
15,1,1,False,151315,49.66,72937.29,6665.52,13014.67,6310.18,1,0,0,2
16,1,1,False,151315,50.25,20107.75,3163.89,15657.30,5812.86,1,0,0,2
17,1,1,False,151315,48.01,10610.74,261.46,25.54,2747.59,1,0,0,3
18,1,1,False,151315,50.81,5000.58,290.46,606.15,3697.11,1,0,0,3
19,1,1,False,151315,55.33,3808.13,0.00,2616.60,1909.17,1,0,0,3
20,1,1,False,151315,63.42,12553.98,0.00,6787.75,2545.66,1,0,0,3
21,1,1,False,151315,51.00,13067.46,0.00,122.93,3903.80,1,0,0,3
22,1,1,False,151315,58.59,12872.34,5687.86,478.04,5092.33,1,0,0,4
23,1,1,False,151315,62.72,3672.43,932.58,949.07,2836.64,1,0,0,4
24,1,1,False,151315,67.10,3530.36,3.95,458.76,2062.05,1,0,0,4
25,1,1,False,151315,59.23,2387.72,0.00,516.28,1421.63,1,0,0,4
26,1,1,False,151315,66.66,2298.63,2.00,55.46,1301.04,1,0,0,5
27,1,1,False,151315,63.90,4624.61,83.88,1618.31,8144.90,1,0,0,5
28,1,1,False,151315,69.53,16170.50,92.00,4127.24,6206.97,1,0,0,5
29,1,1,False,151315,77.19,7959.89,178.00,3152.57,2938.70,1,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115034,45,98,False,118221,32.87,1341.33,30325.14,35.85,3682.17,0,1,0,1
115035,45,98,False,118221,38.78,3877.36,15559.85,152.18,2403.14,0,1,0,1
115036,45,98,False,118221,41.45,14746.10,4071.06,483.58,1467.78,0,1,0,1
115037,45,98,False,118221,26.49,3130.28,1362.10,332.68,1361.74,0,1,0,1
115038,45,98,False,118221,34.92,14508.96,1092.53,26424.02,700.93,0,1,0,2
115039,45,98,True,118221,28.99,53311.88,531.33,24823.94,3233.44,0,1,0,2
115040,45,98,False,118221,35.87,9362.02,2017.68,5012.39,6411.71,0,1,0,2
115041,45,98,False,118221,31.48,10781.51,2735.67,1516.76,3061.21,0,1,0,2
115042,45,98,False,118221,39.72,6614.32,147.82,27.55,1668.95,0,1,0,3
115043,45,98,False,118221,36.13,16382.54,88.67,3096.92,3486.91,0,1,0,3
115044,45,98,False,118221,42.81,9867.03,0.00,912.87,1360.36,0,1,0,3
115045,45,98,False,118221,36.55,11923.74,0.00,1764.47,1647.31,0,1,0,3
115046,45,98,False,118221,40.68,5444.00,0.00,53.90,1722.11,0,1,0,3
115047,45,98,False,118221,43.94,16427.83,5341.41,1523.83,1743.09,0,1,0,4
115048,45,98,False,118221,57.39,8760.15,1713.11,1302.31,1380.74,0,1,0,4
115049,45,98,False,118221,56.27,1399.81,39.89,60.83,1445.05,0,1,0,4
115050,45,98,False,118221,50.64,1260.65,0.00,40.51,2476.18,0,1,0,4
115051,45,98,False,118221,56.07,8345.40,6.00,3580.32,2242.24,0,1,0,5
115052,45,98,False,118221,58.86,4689.18,440.82,375.22,5738.20,0,1,0,5
115053,45,98,False,118221,60.59,4515.35,667.88,522.70,2541.62,0,1,0,5
115054,45,98,False,118221,67.11,3249.34,481.82,1183.23,1309.30,0,1,0,5
115055,45,98,False,118221,65.88,6474.49,411.38,9.38,4227.27,0,1,0,5
115056,45,98,False,118221,70.71,9977.82,744.29,4825.71,3597.34,0,1,0,6
115057,45,98,False,118221,70.01,2471.44,517.87,2612.33,3459.39,0,1,0,6
115058,45,98,False,118221,70.13,4989.34,385.31,2463.42,3117.94,0,1,0,6
115059,45,98,False,118221,76.05,4842.29,975.03,2449.97,3169.69,0,1,0,6
115060,45,98,False,118221,77.50,9090.48,2268.58,5797.47,1514.93,0,1,0,7
115061,45,98,False,118221,79.37,3789.94,1827.31,744.84,2150.36,0,1,0,7
115062,45,98,False,118221,82.84,2961.49,1047.07,363.00,1059.46,0,1,0,7
115063,45,98,False,118221,76.06,212.02,851.73,10.88,1864.57,0,1,0,7

In [14]:
predicted_test = best_model.predict(dataset_test)

In [15]:
dataset_test['weeklySales'] = predicted_test
dataset_test['Date'] = column_date
dataset_test['id'] = dataset_test['Store'].astype(str) + '_' +  dataset_test['Dept'].astype(str) + '_' +  dataset_test['Date'].astype(str)
dataset_test = dataset_test[['id', 'weeklySales']]
dataset_test = dataset_test.rename(columns={'id': 'Id', 'weeklySales': 'Weekly_Sales'})

In [16]:
dataset_test.to_csv('outputknnnnnn.csv', index=False)